permalink: /:title

plugins:
  - jekyll-sitemap

safe: true
lsi: false

highlighter: rouge

comments :
  provider : disqus
  disqus :
    short_name : usethesource

name: Use The Source
title: Use The Source Open Meta Software Community

production_url: http://www.usethesource.io

exclude: ["README.md"]

blogname: Use The Source Blog 
description: Blog for Use The Source Open Meta Software Community
url: http://www.usethesource.io
